#!/usr/bin/env python
# coding: utf-8

import os
import pandas as pd
import geopandas as gpd

from shapely.ops import linemerge
from shapely.geometry import (
    LineString,
    MultiLineString
)


def main(paid_parking, limit):
    """
    Pré-traitement du stationnement tarifé.
    Gère les noms de colonnes exotiques (nLongitude, sNoPlace...) et la géométrie.
    """
    if paid_parking is None:
        return None

    # Map 'Hungarian' notation names from CSV (sNoPlace, nLongitude) to standard names
    # based on real data inspection.
    rename_map = {
        'nLongitude': 'Longitude',
        'nLatitude': 'Latitude',
        'sNoPlace': 'No_Place',
        'nTarifHoraire': 'Tarif_Hr',
        'sNomRue': 'Nom_Rue',
        'sGenre': 'Genre',
        'sStatut': 'Statut',
        'sType': 'Type',
        'sLocalisation': 'Localisation'
    }
    # Apply renaming (ignore errors if a column is missing)
    paid_parking.rename(columns=rename_map, inplace=True)
    
# Create fallbacks so post-processing does not crash.    
    if 'SK_D_Troncon' not in paid_parking.columns:
# Use Street Name as default segment identifier        
        if 'Nom_Rue' in paid_parking.columns:
            paid_parking['SK_D_Troncon'] = paid_parking['Nom_Rue']
        else:
            paid_parking['SK_D_Troncon'] = 'Inconnu'

    if 'SK_D_Place' not in paid_parking.columns:
        # Use No_Place as unique spot ID
        if 'No_Place' in paid_parking.columns:
            paid_parking['SK_D_Place'] = paid_parking['No_Place']
        else:
            paid_parking['SK_D_Place'] = paid_parking.index.astype(str)

    if not isinstance(paid_parking, gpd.GeoDataFrame):
        # Use renamed Longitude/Latitude columns and verify they exist after renaming
        if 'Longitude' in paid_parking.columns and 'Latitude' in paid_parking.columns:
            geometry = gpd.points_from_xy(paid_parking.Longitude, paid_parking.Latitude)
        else:
            print("Warning: Longitude/Latitude columns not found. Automatic search...")
            cols = paid_parking.columns
            lon_col = next((c for c in cols if 'long' in c.lower()), None)
            lat_col = next((c for c in cols if 'lat' in c.lower()), None)
            
            if lon_col and lat_col:
                geometry = gpd.points_from_xy(paid_parking[lon_col], paid_parking[lat_col])
            else:
                raise ValueError("Unable to find GPS coordinates in the parking file.")

        paid_parking = gpd.GeoDataFrame(
            paid_parking,
            geometry=geometry,
            crs='epsg:4326'
        )
    else:
        if paid_parking.crs is None:
             paid_parking.set_crs('epsg:4326', inplace=True)
    
    if not limit.empty:
        if paid_parking.crs != limit.crs:
            paid_parking = paid_parking.to_crs(limit.crs)
        
        paid_parking = gpd.sjoin(
            paid_parking, 
            limit, 
            predicate='within', 
            how='inner'
        ).drop(columns='index_right')

    return paid_parking


def post_processing(buff_length=7):
    """
    Post-processing to group spots into segments.
    Requires files generated by SharedStreets (shst).
    """
    matched_path = './output/shst/paid_parking_preprocessed.matched.geojson'
    buffered_path = './output/shst/paid_parking_preprocessed.buffered.geojson'
    
    if not os.path.exists(matched_path) or not os.path.exists(buffered_path):
        print("\t[Info] SharedStreets files missing. Parking meter post-processing skipped.")
        return

    place_loc = gpd.read_file(matched_path)

    place_loc['start'] = place_loc.location - (buff_length/2)
    place_loc['end'] = place_loc.location + (buff_length/2)

    paid_parking_buff = gpd.read_file(buffered_path)
    paid_parking_buff[['loc_start', 'loc_end']] = place_loc[['start', 'end']]
    
    sort_cols = []
    if 'pp_sk_d_troncon' in paid_parking_buff.columns: sort_cols.append('pp_sk_d_troncon')
    if 'pp_no_place' in paid_parking_buff.columns: sort_cols.append('pp_no_place')
    
    if sort_cols:
        paid_parking_buff.sort_values(sort_cols, inplace=True)

    if 'pp_sk_d_troncon' in paid_parking_buff.columns:
        g = paid_parking_buff.groupby('pp_sk_d_troncon')
        res = []
        for _, d in g:
            dd = d[:-1].reset_index().intersects(d[1:].reset_index())
            cluster_lines = [0]
            cluster_id = 0
            for i in range(dd.shape[0]):
                if dd[i] == False:
                    cluster_id += 1
                cluster_lines.append(cluster_id)

            d['cluster_id'] = cluster_lines
            res.append(d)
        paid_parking_buff = pd.concat(res)
    else:
        paid_parking_buff['cluster_id'] = 0

    possible_columns = [
        'referenceId', 'sideOfStreet', 
        'pp_sk_d_place', 'pp_no_place', 
        'pp_sk_d_troncon', 'pp_tarif_hr', 
        'geometry', 'loc_start', 'loc_end'
    ]
    columns = [c for c in possible_columns if c in paid_parking_buff.columns]
    
    res = []
    
    group_keys = ['referenceId', 'cluster_id']
    if 'pp_sk_d_troncon' in paid_parking_buff.columns:
        group_keys.append('pp_sk_d_troncon')
        
    group_keys = [k for k in group_keys if k in paid_parking_buff.columns]
    
    if not group_keys:
        print("\t[Error] Unable to group parking meters (missing keys).")
        return

    g = paid_parking_buff.groupby(group_keys)

    for _, data in g:
        if data.shape[0] == 1:
            res.append(list(data[columns].values[0]))
            continue


        place_to_line = linemerge(data['geometry'].to_list())
        
        row_data = {col: data[col].iloc[0] for col in columns}
        
        geom_val = LineString([place_to_line.geoms[0].coords[0], place_to_line.geoms[-1].coords[-1]]) if isinstance(place_to_line, MultiLineString) else place_to_line
        row_data['geometry'] = geom_val
        
        row_data['loc_start'] = data['loc_start'].min()
        row_data['loc_end'] = data['loc_end'].max()
        
        if 'pp_sk_d_place' in columns:
            row_data['pp_sk_d_place'] = list(data['pp_sk_d_place'].values)
        if 'pp_no_place' in columns:
            row_data['pp_no_place'] = list(data['pp_no_place'].values)
            
        res.append([row_data[c] for c in columns])


    paid_parking_buff_merge = gpd.GeoDataFrame(data=res, columns=columns, geometry='geometry', crs='epsg:4326')

    for col in ['pp_sk_d_place', 'pp_no_place']:
        if col in paid_parking_buff_merge.columns:
            paid_parking_buff_merge[col] = paid_parking_buff_merge[col].astype(str)

    output_file = './output/shst/paid_parking_postprocessed.buffered.geojson'
    paid_parking_buff_merge.to_file(output_file, driver='GeoJSON')
    print(f"\tFile generated : {output_file}")

if __name__ == '__main__':
    # TODO args passing
    pass